services:
  api:
    build: .
    ports:
      - "7070:8080" #external : internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/X-Judge?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: judge
      SPRING_DATASOURCE_PASSWORD: judge
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: X-Judge
      MYSQL_USER: judge
      MYSQL_PASSWORD: judge
    ports:
      - "3307:3306"  # Changed from 3306:3306 to 3307:3306 to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
