spring.application.name=ScrapingDemo

# Server Configuration
server.port=7070

# Logging Configuration
logging.level.root=INFO
logging.level.com.scraping.scrapingdemo=DEBUG
logging.level.com.microsoft.playwright=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Jackson Configuration
spring.jackson.serialization.indent_output=true
spring.jackson.serialization.write_dates_as_timestamps=false
